# ユーザーのデータ
User.create(
    [
        {username: '鈴木太郎', email: 'sitsumon1@gmail.com', password: '11111111', password_confirmation: '11111111',profile: "こんにちは"},
        {username: '佐々木太郎', email: 'sitsumon2@gmail.com', password: '11111111', password_confirmation: '11111111'},
        {username: '田中太郎', email: 'sitsumon3@gmail.com', password: '11111111', password_confirmation: '11111111'},
        {username: '高橋花子', email: 'kaitou1@gmail.com', password: '11111111', password_confirmation: '11111111'},
        {username: '斎藤花子', email: 'kaitou2@gmail.com', password: '11111111', password_confirmation: '11111111'},
        {username: '池田花子', email: 'kaitou3@gmail.com', password: '11111111', password_confirmation: '11111111'}])
 
Continent.create(
    [
        {name: 'アジア'},
        {name: 'ヨーロッパ'},
        {name: '北米'},
        {name: '中南米'},
        {name: 'オセアニア・ミクロネシア'},
        {name: '中近東'},
        {name: 'アフリカ'},
    ]
)

Country.create(
    [
        {name: '韓国',continent_id: 1, image: "/photos/1.jpg"},
        {name: 'タイ',continent_id: 1, image: "/photos/2.jpg"},
        {name: '台湾',continent_id: 1, image: "/photos/3.jpg"},
        {name: '中国',continent_id: 1, image: "/photos/4.jpg"},
        {name: '香港',continent_id: 1, image: "/photos/5.jpg"},
        {name: 'アフガニスタン',continent_id: 1, image: "/photos/6.jpg"},
        {name: 'インド',continent_id: 1, image: "/photos/7.jpg"},
        {name: 'インドネシア',continent_id: 1, image: "/photos/8.jpg"},
        {name: 'カンボジア',continent_id: 1, image: "/photos/9.jpg"},
        {name: 'シンガポール',continent_id: 1, image: "/photos/10.jpg"},
        {name: 'スリランカ',continent_id: 1, image: "/photos/11.jpg"},
        {name: 'ネパール',continent_id: 1, image: "/photos/12.jpg"},
        {name: 'パキスタン',continent_id: 1, image: "/photos/13.jpg"},
        {name: 'バングラデシュ',continent_id: 1, image: "/photos/14.jpg"},
        {name: '東ティモール',continent_id: 1, image: "/photos/15.jpg"},
        {name: 'フィリピン',continent_id: 1, image: "/photos/16.jpg"},
        {name: 'ブータン',continent_id: 1, image: "/photos/17.jpg"},
        {name: 'ブルネイ',continent_id: 1, image: "/photos/18.jpg"},
        {name: 'ベトナム',continent_id: 1, image: "/photos/19.jpg"},
        {name: 'マカオ',continent_id: 1, image: "/photos/20.jpg"},
        {name: 'マレーシア',continent_id: 1, image: "/photos/21.jpg"},
        {name: 'ミャンマー',continent_id: 1, image: "/photos/22.jpg"},
        {name: 'モルディブ',continent_id: 1, image: "/photos/23.jpg"},
        {name: 'モンゴル',continent_id: 1, image: "/photos/24.jpg"},
        {name: 'ラオス',continent_id: 1, image: "/photos/25.jpg"},
        {name: 'イギリス',continent_id: 2, image: "/photos/26.jpg"},
        {name: 'イタリア',continent_id: 2, image: "/photos/27.jpg"},
        {name: 'スイス',continent_id: 2, image: "/photos/28.jpg"},
        {name: 'スペイン',continent_id: 2, image: "/photos/29.jpg"},
        {name: 'ドイツ',continent_id: 2, image: "/photos/30.jpg"},
        {name: 'フランス',continent_id: 2, image: "/photos/31.jpg"},
        {name: 'フェロー諸島',continent_id: 2, image: "/photos/32.jpg"},
        {name: 'ジブラルタル',continent_id: 2, image: "/photos/33.jpg"},
        {name: 'グリーンランド',continent_id: 2, image: "/photos/34.jpg"},
        {name: 'コソボ',continent_id: 2, image: "/photos/35.jpg"},
        {name: 'スヴァールバル諸島',continent_id: 2, image: "/photos/36.jpg"},
        {name: 'アイスランド',continent_id: 2, image: "/photos/37.jpg"},
        {name: 'アイルランド',continent_id: 2, image: "/photos/38.jpg"},
        {name: 'アゼルバイジャン',continent_id: 2, image: "/photos/39.jpg"},
        {name: 'アルバニア',continent_id: 2, image: "/photos/40.jpg"},
        {name: 'アルメニア',continent_id: 2, image: "/photos/41.jpg"},
        {name: 'アンドラ',continent_id: 2, image: "/photos/42.jpg"},
        {name: 'ウクライナ',continent_id: 2, image: "/photos/43.jpg"},
        {name: 'ウズベキスタン',continent_id: 2, image: "/photos/44.jpg"},
        {name: 'エストニア',continent_id: 2, image: "/photos/45.jpg"},
        {name: 'オーストリア',continent_id: 2, image: "/photos/46.jpg"},
        {name: 'オランダ',continent_id: 2, image: "/photos/47.jpg"},
        {name: 'カザフスタン',continent_id: 2, image: "/photos/48.jpg"},
        {name: 'キプロス',continent_id: 2, image: "/photos/49.jpg"},
        {name: 'ギリシャ',continent_id: 2, image: "/photos/50.jpg"},
        {name: 'キルギス',continent_id: 2, image: "/photos/51.jpg"},
        {name: 'ジョージア',continent_id: 2, image: "/photos/52.jpg"},
        {name: 'クロアチア',continent_id: 2, image: "/photos/53.jpg"},
        {name: 'サンマリノ',continent_id: 2, image: "/photos/54.jpg"},
        {name: 'スウェーデン',continent_id: 2, image: "/photos/55.jpg"},
        {name: 'スロバキア',continent_id: 2, image: "/photos/56.jpg"},
        {name: 'スロベニア',continent_id: 2, image: "/photos/57.jpg"},
        {name: 'セルビア',continent_id: 2, image: "/photos/58.jpg"},
        {name: 'タジキスタン',continent_id: 2, image: "/photos/59.jpg"},
        {name: 'チェコ',continent_id: 2, image: "/photos/60.jpg"},
        {name: 'デンマーク',continent_id: 2, image: "/photos/61.jpg"},
        {name: 'トルコ',continent_id: 2, image: "/photos/62.jpg"},
        {name: 'ノルウェー',continent_id: 2, image: "/photos/63.jpg"},
        {name: 'ハンガリー',continent_id: 2, image: "/photos/64.jpg"},
        {name: 'フィンランド',continent_id: 2, image: "/photos/65.jpg"},
        {name: 'ブルガリア',continent_id: 2, image: "/photos/66.jpg"},
        {name: 'ベラルーシ',continent_id: 2, image: "/photos/67.jpg"},
        {name: 'ベルギー',continent_id: 2, image: "/photos/68.jpg"},
        {name: 'ポーランド',continent_id: 2, image: "/photos/69.jpg"},
        {name: 'ボスニア・ヘルツェゴビナ',continent_id: 2, image: "/photos/70.jpg"},
        {name: 'ポルトガル',continent_id: 2, image: "/photos/71.jpg"},
        {name: '北マケドニア共和国',continent_id: 2, image: "/photos/72.jpg"},
        {name: 'マルタ',continent_id: 2, image: "/photos/73.jpg"},
        {name: 'モナコ',continent_id: 2, image: "/photos/74.jpg"},
        {name: 'モルドバ',continent_id: 2, image: "/photos/75.jpg"},
        {name: 'モンテネグロ',continent_id: 2, image: "/photos/76.jpg"},
        {name: 'ラトビア',continent_id: 2, image: "/photos/77.jpg"},
        {name: 'リトアニア',continent_id: 2, image: "/photos/78.jpg"},
        {name: 'リヒテンシュタイン',continent_id: 2, image: "/photos/79.jpg"},
        {name: 'ルーマニア',continent_id: 2, image: "/photos/80.jpg"},
        {name: 'ルクセンブルク',continent_id: 2, image: "/photos/81.jpg"},
        {name: 'ロシア',continent_id: 2, image: "/photos/82.jpg"},
        {name: 'アメリカ',continent_id: 3, image: "/photos/83.jpg"},
        {name: 'カナダ',continent_id: 3, image: "/photos/84.jpg"},
        {name: 'ハワイ',continent_id: 3, image: "/photos/85.jpg"},
        {name: 'ブラジル',continent_id: 4, image: "/photos/86.jpg"},
        {name: 'ペルー',continent_id: 4, image: "/photos/87.jpg"},
        {name: 'メキシコ',continent_id: 4, image: "/photos/88.jpg"},
        {name: 'アンギラ',continent_id: 4, image: "/photos/89.jpg"},
        {name: 'サン・バルテルミ',continent_id: 4, image: "/photos/90.jpg"},
        {name: 'BES諸島',continent_id: 4, image: "/photos/91.jpg"},
        {name: 'キュラソー',continent_id: 4, image: "/photos/92.jpg"},
        {name: 'グアドループ',continent_id: 4, image: "/photos/93.jpg"},
        {name: 'アルゼンチン',continent_id: 4, image: "/photos/94.jpg"},
        {name: 'アルバ',continent_id: 4, image: "/photos/95.jpg"},
        {name: 'アンティグア・バーブーダ',continent_id: 4, image: "/photos/96.jpg"},
        {name: 'ウルグアイ',continent_id: 4, image: "/photos/97.jpg"},
        {name: '英領ヴァージン諸島',continent_id: 4, image: "/photos/98.jpg"},
        {name: 'エクアドル',continent_id: 4, image: "/photos/99.jpg"},
        {name: 'エルサルバドル',continent_id: 4, image: "/photos/100.jpg"},
        {name: 'ガイアナ',continent_id: 4, image: "/photos/101.jpg"},
        {name: 'キューバ',continent_id: 4, image: "/photos/102.jpg"},
        {name: 'グアテマラ',continent_id: 4, image: "/photos/103.jpg"},
        {name: 'グレナダ',continent_id: 4, image: "/photos/104.jpg"},
        {name: 'ケイマン諸島',continent_id: 4, image: "/photos/105.jpg"},
        {name: 'コスタリカ',continent_id: 4, image: "/photos/106.jpg"},
        {name: 'コロンビア',continent_id: 4, image: "/photos/107.jpg"},
        {name: 'ジャマイカ',continent_id: 4, image: "/photos/108.jpg"},
        {name: 'スリナム',continent_id: 4, image: "/photos/109.jpg"},
        {name: 'セント・マーチン島',continent_id: 4, image: "/photos/110.jpg"},
        {name: 'セントクリストファー・ネイビス',continent_id: 4, image: "/photos/111.jpg"},
        {name: 'セントビンセント・グレナディーン',continent_id: 4, image: "/photos/112.jpg"},
        {name: 'セントルシア',continent_id: 4, image: "/photos/113.jpg"},
        {name: 'チリ',continent_id: 4, image: "/photos/114.jpg"},
        {name: 'ドミニカ共和国',continent_id: 4, image: "/photos/115.jpg"},
        {name: 'ドミニカ国',continent_id: 4, image: "/photos/116.jpg"},
        {name: 'トリニダード・トバゴ',continent_id: 4, image: "/photos/117.jpg"},
        {name: 'ニカラグア',continent_id: 4, image: "/photos/118.jpg"},
        {name: 'ハイチ',continent_id: 4, image: "/photos/119.jpg"},
        {name: 'パナマ',continent_id: 4, image: "/photos/120.jpg"},
        {name: 'バハマ',continent_id: 4, image: "/photos/121.jpg"},
        {name: 'バミューダ諸島',continent_id: 4, image: "/photos/122.jpg"},
        {name: 'パラグアイ',continent_id: 4, image: "/photos/123.jpg"},
        {name: 'バルバドス',continent_id: 4, image: "/photos/124.jpg"},
        {name: 'プエルトリコ',continent_id: 4, image: "/photos/125.jpg"},
        {name: '仏領ギアナ',continent_id: 4, image: "/photos/126.jpg"},
        {name: '米領ヴァージン諸島',continent_id: 4, image: "/photos/127.jpg"},
        {name: 'ベネズエラ',continent_id: 4, image: "/photos/128.jpg"},
        {name: 'ベリーズ',continent_id: 4, image: "/photos/129.jpg"},
        {name: 'ボネール',continent_id: 4, image: "/photos/130.jpg"},
        {name: 'ボリビア',continent_id: 4, image: "/photos/131.jpg"},
        {name: 'ホンジュラス',continent_id: 4, image: "/photos/132.jpg"},
        {name: 'マルチニーク',continent_id: 4, image: "/photos/133.jpg"},
        {name: 'タークス・カイコス諸島',continent_id: 4, image: "/photos/134.jpg"},
        {name: 'オーストラリア',continent_id: 5, image: "/photos/135.jpg"},
        {name: '北マリアナ諸島',continent_id: 5, image: "/photos/136.jpg"},
        {name: 'ニュージーランド',continent_id: 5, image: "/photos/137.jpg"},
        {name: 'ノーフォーク島',continent_id: 5, image: "/photos/138.jpg"},
        {name: 'キリバス',continent_id: 5, image: "/photos/139.jpg"},
        {name: 'グアム',continent_id: 5, image: "/photos/140.jpg"},
        {name: 'クック諸島',continent_id: 5, image: "/photos/141.jpg"},
        {name: 'サモア',continent_id: 5, image: "/photos/142.jpg"},
        {name: 'ソロモン諸島',continent_id: 5, image: "/photos/143.jpg"},
        {name: 'タヒチ',continent_id: 5, image: "/photos/144.jpg"},
        {name: 'トンガ',continent_id: 5, image: "/photos/145.jpg"},
        {name: 'ニウエ',continent_id: 5, image: "/photos/146.jpg"},
        {name: 'ニューカレドニア',continent_id: 5, image: "/photos/147.jpg"},
        {name: 'バヌアツ',continent_id: 5, image: "/photos/148.jpg"},
        {name: 'パプアニューギニア',continent_id: 5, image: "/photos/149.jpg"},
        {name: 'パラオ',continent_id: 5, image: "/photos/150.jpg"},
        {name: 'フィジー',continent_id: 5, image: "/photos/151.jpg"},
        {name: '米領サモア',continent_id: 5, image: "/photos/152.jpg"},
        {name: 'マーシャル諸島',continent_id: 5, image: "/photos/153.jpg"},
        {name: 'ミクロネシア',continent_id: 5, image: "/photos/154.jpg"},
        {name: 'アラブ首長国連邦',continent_id: 6, image: "/photos/155.jpg"},
        {name: 'イスラエル',continent_id: 6, image: "/photos/156.jpg"},
        {name: 'イラク',continent_id: 6, image: "/photos/157.jpg"},
        {name: 'イラン',continent_id: 6, image: "/photos/158.jpg"},
        {name: 'オマーン',continent_id: 6, image: "/photos/159.jpg"},
        {name: 'カタール',continent_id: 6, image: "/photos/160.jpg"},
        {name: 'クウェート',continent_id: 6, image: "/photos/161.jpg"},
        {name: 'サウジアラビア',continent_id: 6, image: "/photos/162.jpg"},
        {name: 'シリア',continent_id: 6, image: "/photos/163.jpg"},
        {name: 'バーレーン',continent_id: 6, image: "/photos/164.jpg"},
        {name: 'ヨルダン',continent_id: 6, image: "/photos/165.jpg"},
        {name: 'レバノン',continent_id: 6, image: "/photos/166.jpg"},
        {name: 'エジプト',continent_id: 7, image: "/photos/167.jpg"},
        {name: 'ケニア',continent_id: 7, image: "/photos/168.jpg"},
        {name: 'ジンバブエ',continent_id: 7, image: "/photos/169.jpg"},
        {name: 'チュニジア',continent_id: 7, image: "/photos/170.jpg"},
        {name: '南アフリカ共和国',continent_id: 7, image: "/photos/171.jpg"},
        {name: 'モロッコ',continent_id: 7, image: "/photos/172.jpg"},
        {name: 'アルジェリア',continent_id: 7, image: "/photos/173.jpg"},
        {name: 'アンゴラ',continent_id: 7, image: "/photos/174.jpg"},
        {name: 'ウガンダ',continent_id: 7, image: "/photos/175.jpg"},
        {name: 'エチオピア',continent_id: 7, image: "/photos/176.jpg"},
        {name: 'エリトリア',continent_id: 7, image: "/photos/177.jpg"},
        {name: 'ガーナ',continent_id: 7, image: "/photos/178.jpg"},
        {name: 'カーボベルデ',continent_id: 7, image: "/photos/179.jpg"},
        {name: 'ガボン',continent_id: 7, image: "/photos/180.jpg"},
        {name: 'カメルーン',continent_id: 7, image: "/photos/181.jpg"},
        {name: 'ガンビア',continent_id: 7, image: "/photos/182.jpg"},
        {name: 'ギニア',continent_id: 7, image: "/photos/183.jpg"},
        {name: 'ギニアビサウ',continent_id: 7, image: "/photos/184.jpg"},
        {name: 'コートジボワール',continent_id: 7, image: "/photos/185.jpg"},
        {name: 'コモロ',continent_id: 7, image: "/photos/186.jpg"},
        {name: 'コンゴ共和国',continent_id: 7, image: "/photos/187.jpg"},
        {name: 'コンゴ民主共和国',continent_id: 7, image: "/photos/188.jpg"},
        {name: 'サントメ・プリンシペ',continent_id: 7, image: "/photos/189.jpg"},
        {name: 'ザンビア',continent_id: 7, image: "/photos/190.jpg"},
        {name: 'シエラレオネ',continent_id: 7, image: "/photos/191.jpg"},
        {name: 'ジブチ',continent_id: 7, image: "/photos/192.jpg"},
        {name: 'スーダン',continent_id: 7, image: "/photos/193.jpg"},
        {name: 'エスワティニ',continent_id: 7, image: "/photos/194.jpg"},
        {name: 'セーシェル',continent_id: 7, image: "/photos/195.jpg"},
        {name: '赤道ギニア',continent_id: 7, image: "/photos/196.jpg"},
        {name: 'セネガル',continent_id: 7, image: "/photos/197.jpg"},
        {name: 'タンザニア',continent_id: 7, image: "/photos/198.jpg"},
        {name: 'チャド',continent_id: 7, image: "/photos/199.jpg"},
        {name: 'トーゴ',continent_id: 7, image: "/photos/200.jpg"},
        {name: 'ナイジェリア',continent_id: 7, image: "/photos/201.jpg"},
        {name: 'ナミビア',continent_id: 7, image: "/photos/202.jpg"},
        {name: 'ニジェール',continent_id: 7, image: "/photos/203.jpg"},
        {name: 'ブルキナファソ',continent_id: 7, image: "/photos/204.jpg"},
        {name: 'ブルンジ',continent_id: 7, image: "/photos/205.jpg"},
        {name: 'ベナン',continent_id: 7, image: "/photos/206.jpg"},
        {name: 'ボツワナ',continent_id: 7, image: "/photos/207.jpg"},
        {name: 'マダガスカル',continent_id: 7, image: "/photos/208.jpg"},
        {name: 'マラウイ',continent_id: 7, image: "/photos/209.jpg"},
        {name: 'マリ',continent_id: 7, image: "/photos/210.jpg"},
        {name: 'モーリシャス',continent_id: 7, image: "/photos/211.jpg"},
        {name: 'モーリタニア',continent_id: 7, image: "/photos/212.jpg"},
        {name: 'モザンビーク',continent_id: 7, image: "/photos/213.jpg"},
        {name: 'リビア',continent_id: 7, image: "/photos/214.jpg"},
        {name: 'リベリア',continent_id: 7, image: "/photos/215.jpg"},
        {name: 'ルワンダ',continent_id: 7, image: "/photos/216.jpg"},
        {name: 'レソト',continent_id: 7, image: "/photos/217.jpg"},
        {name: 'レユニオン',continent_id: 7, image: "/photos/218.jpg"}
    ]
)        

Tag.create(
    [
        {name: '観光'},
        {name: 'ホテル'},
        {name: 'ショッピング'},
        {name: 'グルメ'},
        {name: '交通'},
        {name: '治安'},
        {name: 'トラブル'},
        {name: '通貨・クレジットカード'},
        {name: '天候・気候'},
        {name: '郵便・電話'},
        {name: 'Wi-Fiレンタル・Wi-Fiスポット・SIMカード'}
      ])
Question.create(
    [
        {title: '東京のお土産で喜ばれるもの', body: '今週末東京に行きますが、東京土産で喜ばれるものありますか？', user_id: 1,country_id:1,tag_id: 2},
        {title: '好きな動物', body: '一番好きな動物は何ですか？', user_id: 1,country_id: 2, tag_id: 4},
        {title: '美味しいご飯や', body: '名古屋周辺の美味しいご飯屋さん教えてください', user_id: 2,country_id: 3, tag_id: 9},
        {title: '明日の天気', body: '明日の天気は？', user_id: 2,country_id: 4, tag_id: 11},
        {title: '読書時間について', body: '一日の読書時間はどれぐらい？', user_id: 3,country_id: 5, tag_id: 7},
        {title: '英語の勉強法', body: '英語はどうやって勉強したらいいですか？', user_id: 3,country_id: 6, tag_id: 4}])
 
Answer.create(
    [
        {body: '東京ばな奈じゃないですか？', question_id: 1, user_id: 4},
        {body: 'ラスクみたいなやつ', question_id: 1, user_id: 5},
        {body: '中華まん', question_id: 1, user_id: 6},
        {body: '猫', question_id: 2, user_id: 4},
        {body: '犬', question_id: 2, user_id: 5},
        {body: 'とり', question_id: 2, user_id: 6},
        {body: '矢場とん', question_id: 3, user_id: 4},
        {body: '山ちゃん', question_id: 3, user_id: 5},
        {body: 'みせん', question_id: 3, user_id: 6},
        {body: '晴れ', question_id: 4, user_id: 4},
        {body: '曇り', question_id: 4, user_id: 5},
        {body: '雨', question_id: 4, user_id: 6},
        {body: '1時間', question_id: 5, user_id: 4},
        {body: '2時間', question_id: 5, user_id: 5},
        {body: '3時間', question_id: 5, user_id: 6},
        {body: '特かく話す', question_id: 6, user_id: 4},
        {body: '単語の勉強', question_id: 6, user_id: 5},
        {body: 'レッスンに行く', question_id: 6, user_id: 6}])
 
Reaction.create(
    [
        {body: '東京ばな奈いいですね', user_id: 1, answer_id: 1},
        {body: '猫いいですね！', user_id: 1, answer_id: 4},
        {body: '矢場とんいいですね！', user_id: 3, answer_id: 7}])






 #質問にタグをつける
# questions = Question.all
# questions.each do |q|
#     q.tag = rand(1..11)
# end

# activeadmin(管理画面)に入るためのユーザーです。ターミナルで「rails g active_admin:install」を実行後作成されます。
AdminUser.create!(email: 'admin@gmail.com', password: '11111111', password_confirmation: '11111111') if Rails.env.development?